# Site
name: "Devkimson"
title: "Devkimson"
description: "í•˜ë£¨ì˜ ë°œìì·¨ë¥¼ ê¸°ë¡í•˜ëŠ” ì˜ˆë¹„ ê°œë°œìì˜ ë¸”ë¡œê·¸"
logo: "assets/images/logo-k-color.png"
favicon: "assets/images/logo-k-color.png"
url: "https://kkn1125.github.io"
baseurl: ""
disqus: "devkimson"
email: "chaplet01@gmail.com"
# mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"
google_analytics: "UA-179074259-1"
top: <a href="#" id="gotop"><i class="fas fa-arrow-alt-circle-up fa-2x"></i></a>
todo: true

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

authors:
  Kimson:
    name: kimson
    site: https://kkn1125.github.io
    profile: assets/images/kim.jpg
    avatar: assets/images/profilecard.jpg
    bio: "í•˜ë£¨í•˜ë£¨ ê²Œì„ë¦¬í•˜ì§€ ì•Šê³  ë‚˜ë§Œì˜ ë°©ì‹ìœ¼ë¡œ ë°œì „í•´ë‚˜ê°€ëŠ” ì˜ˆë¹„ ê°œë°œìì…ë‹ˆë‹¤ ğŸ™‹â€â™‚ï¸"
    email: chaplet01@gmail.com
    twitter: https://twitter.com/wowthemesnet
    github: https://github.com/kkn1125

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: kimson
      avatar: assets/images/profilecard.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown

kramdown:
  entity_output: :as_input
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

highlighter: rouge

jekyll-archives:
  enabled:
  - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Where things are
jekyll-spaceship:
  # default enabled processors
  processors:
    - table-processor
    - mathjax-processor
    - plantuml-processor
    - mermaid-processor
    - polyfill-processor
    - media-processor
    - emoji-processor
    - element-processor
  mathjax-processor:
    src:
      - https://polyfill.io/v3/polyfill.min.js?features=es6
      - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    config:
      tex:
        inlineMath:
          - ["$", "$"]
          - ['\(', '\)']
        displayMath:
          - ["$$", "$$"]
          - ['\[', '\]']
      svg:
        fontCache: "global"
    optimize: # optimization on building stage to check and add mathjax scripts
      enabled: true # value `false` for adding to all pages
      include: [] # include patterns for math expressions checking (regexp)
      exclude: [] # exclude patterns for math expressions checking (regexp)
  plantuml-processor:
    mode: default # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: plantuml
    syntax:
      code: "plantuml!"
      custom: ["@startuml", "@enduml"]
    src: http://www.plantuml.com/plantuml/svg/
  mermaid-processor:
    mode: default # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: mermaid
    syntax:
      code: "mermaid!"
      custom: ["@startmermaid", "@endmermaid"]
    config:
      theme: default
    src: https://mermaid.ink/svg/
  media-processor:
    default:
      id: "media-{id}"
      class: "media"
      width: "100%"
      height: 350
      frameborder: 0
      style: "max-width: 600px; outline: none;"
      allow: "encrypted-media; picture-in-picture"
  emoji-processor:
    css:
      class: emoji
    src: https://github.githubassets.com/images/icons/emoji/

# Paginate
paginate: 10
paginate_path: /page:num/

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.markdown,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
  ]
